#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    T = 10
    print(T)
    X = "FOX."
    for _ in range(T):
        N = random.randint(10, 50)
        S = [X[random.randint(0, 2)]]
        for _ in range(N):
            S.append(X[random.randint(0, 3)])
        S = ''.join(S)
        print(N)
        print(S)

if __name__ == "__main__":
    main()
