#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    H = random.randint(2, 100)  # TODO: edit here
    W = random.randint(2, 100)  # TODO: edit here
    A = [[None for _ in range(W)] for _ in range(H)]
    C = random.randint(1, int(1e9))  # TODO: edit here
    for j in range(H):
        for i in range(W):
            A[j][i] = random.randint(1, int(1e9))  # TODO: edit here
    print(H, W, C)
    for j in range(H):
        print(*[A[j][i] for i in range(W)])

if __name__ == "__main__":
    main()
