#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 500)  # TODO: edit here
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = random.randint(-100, 100)  # TODO: edit here
    print(N)
    for i in range(N):
        print(a[i])

if __name__ == "__main__":
    main()
