#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.7.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    S = random.randint(1, 10)  # TODO: edit here
    Q = random.randint(1, 10)  # TODO: edit here
    Query = [None for _ in range(Q)]
    for i in range(Q):
        Query[i] = random.randint(1, 10)  # TODO: edit here
    print(N)
    print(S)
    print(Q)
    for i in range(Q):
        print(Query[i])

if __name__ == "__main__":
    main()
