#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.7.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    M = random.randint(1, 10)  # TODO: edit here
    A = [None for _ in range(M)]
    for i in range(M):
        A[i] = random.randint(1, 10)  # TODO: edit here
    print(N, M)
    print(*[A[i] for i in range(M)])

if __name__ == "__main__":
    main()
