#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(2, 20)  # TODO: edit here
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = random.randint(1, int(1e9))  # TODO: edit here
    Q = random.randint(1, 100)  # TODO: edit here
    Query = [None for _ in range(Q)]
    for i in range(Q):
        l = random.randint(1, N)
        r = random.randint(l, N)
        x = random.randint(1, int(1e9))
        Query[i] = [l, r, x]  # TODO: edit here
    print(N)
    print(*[A[i] for i in range(N)])
    print(Q)
    for i in range(Q):
        print(*Query[i])

if __name__ == "__main__":
    main()
